version: "3.5"
services:
  node:
    image: "node.hopr.public.dappnode.eth:1.0.21"
    build:
      context: .
      args:
        UPSTREAM_VERSION: >-
          2.1.0-rc.1@sha256:233c6aaa40c90f76e74a5b6432e3a36c4ce2d33b05f06c9df33bb2afc0072edf
    ports:
      - "9091:9091/tcp"
      - "9091:9091/udp"
      - "3001"
    volumes:
      - "data:/app/hoprd-db"
    security_opt:
      - "seccomp:unconfined"
    environment:
      RUST_LOG: info
      HOPRD_NETWORK: dufour
      HOPRD_CONFIGURATION_FILE_PATH: /app/hoprd.cfg.yaml
      HOPRD_HOST: "127.0.0.1:9091"
      HOPRD_SAFE_ADDRESS: 0x
      HOPRD_MODULE_ADDRESS: 0x
      HOPRD_HEARTBEAT_THRESHOLD: 60
      HOPRD_HEARTBEAT_INTERVAL: 20
      HOPRD_HEARTBEAT_VARIANCE: 1
      HOPRD_PASSWORD: ""
      HOPRD_PROVIDER: "https://primary.gnosis-chain.rpc.hoprtech.net/"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
  admin:
    image: >-
      europe-west3-docker.pkg.dev/hoprassociation/docker-images/hopr-admin:0.9.1-beta.12
    ports:
      - "3000:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
volumes:
  data: {}
