version: "3.5"
services:
  node:
    # Do not set image field here, it will be set automatically by the sdk.
    build:
      context: .
      args:
        UPSTREAM_VERSION: >-
          2.1.5@sha256:ba5acd2ef4d85b1b3cb5f3245e12c2d6877ca7f404af4a42429f1f362a666846
    ports:
      - "3001:3001/tcp"
      - "9091:9091/tcp"
      - "9091:9091/udp"
      - "9092:9092/tcp"
      - "9092:9092/udp"
      - "9093:9093/tcp"
      - "9093:9093/udp"
      - "9094:9094/tcp"
      - "9094:9094/udp"
      - "9095:9095/tcp"
      - "9095:9095/udp"
      - "9096:9096/tcp"
      - "9096:9096/udp"
      - "9097:9097/tcp"
      - "9097:9097/udp"
      - "9098:9098/tcp"
      - "9098:9098/udp"
      - "9099:9099/tcp"
      - "9099:9099/udp"
    volumes:
      - "db:/app/hoprd-db"
    security_opt:
      - "seccomp:unconfined"
    environment:
      RUST_LOG: info
      HOPRD_CONFIGURATION_FILE_PATH: /app/hoprd.cfg.yaml
      HOPRD_HOST: "127.0.0.1:9091"
      HOPRD_SAFE_ADDRESS: 0x
      HOPRD_MODULE_ADDRESS: 0x
      HOPRD_HEARTBEAT_THRESHOLD: 60
      HOPRD_HEARTBEAT_INTERVAL: 20
      HOPRD_HEARTBEAT_VARIANCE: 1
      HOPRD_PASSWORD: ""
      HOPRD_PROVIDER: ""
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
  admin:
    # The actual image name  will be set automatically by the sdk.
    # This tag only serves to pull the correct image during build.
    build:
      context: ./hopr-admin
    image: >-
      europe-west3-docker.pkg.dev/hoprassociation/docker-images/hopr-admin:2.1.10
    ports:
      - "3000:4677"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
volumes:
  db: {}
