version: "3.5"
services:
  hopr.dnp.dappnode.eth:
    image: "hopr.dnp.dappnode.eth:0.1.0"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: ouagadougou
    ports:
      - "9091"
      - "3000"
      - "3001"
      - "8080"
      - "53"
    volumes:
      - "db:/app/hoprd-db"
    environment:
      DEBUG: hopr*
      DB_PASSWORD: open-sesame-iTwnsPNg0hpagP+o6T0KOwiH9RQ0
      API_TOKEN: yLWk!W@Z9G&14O^xbtpBc
    restart: unless-stopped
volumes:
  db: {}
