version: "3.5"
services:
  node:
    image: "node.hopr.public.dappnode.eth:1.0.12"
    build:
      context: .
      args:
        UPSTREAM_VERSION: providence
    ports:
      - "9091:9091/tcp"
      - "9091:9091/udp"
      - "3001"
    volumes:
      - "db:/app/hoprd-db"
    environment:
      - DEBUG=hopr*
      - HOPRD_ANNOUNCE=true
      - HOPRD_NETWORK=dufour
      - "HOPRD_PASSWORD=open-sesame-iTwnsPNg0hpagP+o6T0KOwiH9RQ0"
      - HOPRD_API=true
      - HOPRD_API_HOST=0.0.0.0
      - HOPRD_API_PORT=3001
      - HOPRD_HEALTH_CHECK=true
      - HOPRD_HEALTH_CHECK_HOST=0.0.0.0
      - HOPRD_HEALTH_CHECK_PORT=8080
      - HOPRD_API_TOKEN=!5qxc9Lp1BE7IFQ-nrtttU
      - HOPRD_DISABLE_API_AUTHENTICATION=true
      - HOPRD_IDENTITY=/app/hoprd-db/.hopr-identity
      - HOPRD_DATA=/app/hoprd-db/data
      - HOPRD_INIT=true
      - HOPRD_HOST=127.0.0.1:9091
      - HOPRD_SAFE_ADDRESS=0x
      - HOPRD_MODULE_ADDRESS=0x
      - HOPRD_ALLOW_PRIVATE_NODE_CONNECTIONS=false
      - HOPRD_HEARTBEAT_THRESHOLD=60000
      - HOPRD_HEARTBEAT_INTERVAL=20000
      - HOPRD_PASSWORD=open-sesame-iTwnsPNg0hpagP+o6T0KOwiH9RQ0 # keep the value, it gets immediately overwritten automatically during setup 
      - "HOPRD_PROVIDER=https://provider-proxy.hoprnet.workers.dev/xdai_mainnet"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
  admin:
    image: hopr-admin
    build:
      context: https://github.com/hoprnet/hopr-admin.git#f15eaaf2031b061b6eb304b8a5c4ec36df603827:.
      dockerfile: scripts/NodeAdmin.Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  db: {}
